import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service" };

const h2 = "mt-8 text-lg font-semibold";
const p = "mt-2 text-sm leading-relaxed text-muted-foreground";

export default function TermsPage() {
  return (
    <article className="mx-auto w-full max-w-2xl px-6 py-14">
      <h1 className="text-3xl font-semibold tracking-tight">Terms of Service</h1>
      <p className={p}>Last updated September 21, 2026.</p>
      <p className={p}>
        By creating an account or using Callwise you agree to these terms. Callwise is a portfolio project provided to
        demonstrate software, not a commercial service.
      </p>

      <h2 className={h2}>The service</h2>
      <p className={p}>
        Callwise lets you create AI assistants that answer questions using documents you provide. The service is provided
        &quot;as is&quot;, without warranties, and may change, pause or shut down at any time without notice. There is no
        uptime commitment.
      </p>

      <h2 className={h2}>Your content</h2>
      <p className={p}>
        You keep ownership of what you upload. You are responsible for having the right to use it, and you agree not to upload
        sensitive personal data, payment details, health information or anything unlawful. Assistant answers are generated by
        AI and can be wrong, so do not rely on them for legal, medical or financial decisions.
      </p>

      <h2 className={h2}>Acceptable use</h2>
      <p className={p}>
        Do not attempt to disrupt the service, bypass rate limits, probe for vulnerabilities, or use it to send spam or abuse
        others. Accounts that do may be removed.
      </p>

      <h2 className={h2}>Limits</h2>
      <p className={p}>
        Usage limits apply to protect the service, including caps on documents, file size, messages and requests. Phone
        features run on a trial telephony account and are available only to approved numbers.
      </p>

      <h2 className={h2}>Ending your account</h2>
      <p className={p}>
        You can delete your account at any time from Account settings, which permanently removes your data. To the extent
        allowed by law, Callwise is not liable for losses arising from use of the service.
      </p>
    </article>
  );
}
